## 0. python imports

In [1]:
import numpy as np
import pandas as pd
import zipfile

## 1. data loading

In [2]:
zf = zipfile.ZipFile('./data/us-census-demographic-data.zip') 
census = pd.read_csv(zf.open('acs2015_county_data.csv'), index_col='CensusId')

## 2. transformation step

In [17]:
census.head()

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

In [18]:
census.describe()

TotalPop           Men         Women     Hispanic        White  \
count  3.220000e+03  3.220000e+03  3.220000e+03  3220.000000  3220.000000   
mean   9.940935e+04  4.889694e+04  5.051241e+04    11.011522    75.428789   
std    3.193055e+05  1.566813e+05  1.626620e+05    19.241380    22.932890   
min    8.500000e+01  4.200000e+01  4.300000e+01     0.000000     0.000000   
25%    1.121800e+04  5.637250e+03  5.572000e+03     1.900000    64.100000   
50%    2.603500e+04  1.293200e+04  1.305700e+04     3.900000    84.100000   
75%    6.643050e+04  3.299275e+04  3.348750e+04     9.825000    93.200000   
max    1.003839e+07  4.945351e+06  5.093037e+06    99.900000    99.800000   

             Black       Native        Asian      Pacific       Citizen  ...  \
count  3220.000000  3220.000000  3220.000000  3220.000000  3.220000e+03  ...   
mean      8.665497     1.723509     1.229068     0.082733  6.993507e+04  ...   
std      14.279122     7.253115     2.633079     0.734931  2.051189e+05  ...   
min       0.000000     0.000000     0.000000     0.000000  8.000000e+01  ...   
25%       0.500000     0.100000     0.200000     0.000000  8.450500e+03  ...   
50%       1.900000     0.300000     0.500000     0.000000  1.964300e+04  ...   
75%       9.600000     0.600000     1.200000     0.000000  4.992050e+04  ...   
max      85.900000    92.100000    41.600000    35.300000  6.046749e+06  ...   

              Walk  OtherTransp   WorkAtHome  MeanCommute      Employed  \
count  3220.000000  3220.000000  3220.000000  3220.000000  3.220000e+03   
mean      3.323509     1.612733     4.631770    23.278758  4.559352e+04   
std       3.756096     1.670988     3.178772     5.600466  1.496995e+05   
min       0.000000     0.000000     0.000000     4.900000  6.200000e+01   
25%       1.400000     0.900000     2.700000    19.500000  4.550750e+03   
50%       2.400000     1.300000     3.900000    23.000000  1.050800e+04   
75%       4.000000     1.900000     5.600000    26.800000  2.863275e+04   
max      71.200000    39.100000    37.200000    44.000000  4.635465e+06   

       PrivateWork   PublicWork  SelfEmployed   FamilyWork  Unemployment  
count  3220.000000  3220.000000   3220.000000  3220.000000   3220.000000  
mean     74.219348    17.560870      7.931801     0.288106      8.094441  
std       7.863188     6.510354      3.914974     0.455137      4.096114  
min      25.000000     5.800000      0.000000     0.000000      0.000000  
25%      70.500000    13.100000      5.400000     0.100000      5.500000  
50%      75.700000    16.200000      6.900000     0.200000      7.600000  
75%      79.700000    20.500000      9.400000     0.300000      9.900000  
max      88.300000    66.200000     36.600000     9.800000     36.500000  

[8 rows x 34 columns]

## 2.1 arbitrary transformations, etc.

This is the very first step and depends on the particular problem to solve and model to make.

## 2.2 modeling transformations: joins, feature engineering, etc.

This step consists on gathering all the needed data to build the model. It involves extensive research about the problem, meetings with stakeholders, data gobernance teams and more. Usually this step takes most of the time.

## 2.3 transformation to improve ML model performance

### 2.3.1 outlier detection

For n-dimensional outlier / anomaly detection check: https://pyod.readthedocs.io/en/latest/example.html

1D iqr example for `FamilyWork` variable: % in unpaid family work

In [20]:
census['FamilyWork'].head()

CensusId
1001    0.0
1003    0.4
1005    0.1
1007    0.4
1009    0.4
Name: FamilyWork, dtype: float64

In [6]:
census['FamilyWork'].plot(kind='box', grid=True);

In [7]:
q1 = census['FamilyWork'].quantile(0.25)
q3 = census['FamilyWork'].quantile(0.75)
print(f'Q1: {q1} | Q3: {q3}')

Q1: 0.1 | Q3: 0.3


In [8]:
iqr = q3 - q1
print(f'iqr: {iqr:.2f}')

iqr: 0.20


In [9]:
n = 3
upper_fence = q3 + n * iqr
lower_fence = q1 - n * iqr
print(f'upper: {upper_fence:.2f}', 
      f'lower: {lower_fence:.2f}')

upper: 0.90 lower: -0.50


In [10]:
family_work_outlier_filter = census['FamilyWork'] \
                             .between(lower_fence,
                                      upper_fence)

print(f'n_outliers: {len(census) - family_work_outlier_filter.sum()}')

n_outliers: 198


Filter outliers:

In [11]:
census = census.loc[family_work_outlier_filter, :]
census.shape

(3022, 36)

### 2.3.2 scaling

scikit-learn encoders already store learned parameters and are ready to 'transform' new and unseen data.

In [12]:
from sklearn.preprocessing import RobustScaler, StandardScaler

scaler = RobustScaler()
X_numeric_scaled = scaler.fit_transform(census.select_dtypes(include='number'))

In [13]:
pd.DataFrame(X_numeric_scaled).head()

0         1         2       3         4         5    6    7    8   \
0  0.446361  0.421539  0.468354 -0.1625 -0.265517  1.663265  0.4  0.5  0.0   
1  2.790117  2.747765  2.838568  0.0750 -0.013793  0.744898  0.8  0.2  0.0   
2 -0.027567  0.006022 -0.064662  0.0875 -1.286207  4.540816  0.0 -0.1  0.0   
3 -0.100075 -0.076213 -0.127929 -0.2125 -0.310345  1.959184  0.4 -0.4  0.0   
4  0.488059  0.481485  0.492345  0.5875  0.151724 -0.071429  0.2 -0.4  0.0   

         9   ...        24   25        26        27        28        29  \
0  0.427065  ... -0.750000  0.0 -0.740741  0.464789  0.468156 -0.288184   
1  2.830305  ... -0.541667  0.1  0.037037  0.450704  2.842052  0.622478   
2 -0.022511  ... -0.208333  0.2 -0.814815  0.126761 -0.121382 -0.495677   
3 -0.094831  ... -0.708333  0.2 -1.148148  0.788732 -0.132990  0.080692   
4  0.463461  ... -0.583333 -0.9 -0.555556  1.647887  0.399314  0.680115   

         30        31   32        33  
0  0.657534 -0.324324 -1.0 -0.023810  
1 -0.520548 -0.243243  1.0 -0.047619  
2  0.643836  0.162162 -0.5  2.357143  
3  0.000000  0.000000  1.0  0.142857  
4 -0.356164 -0.675676  1.0  0.000000  

[5 rows x 34 columns]

### 2.3.3 one hot encoding

scikit learn version:

In [14]:
census.select_dtypes(include='object').nunique()

State       52
County    1827
dtype: int64

In [15]:
census['County'].value_counts().nlargest(10)

Washington    31
Jefferson     26
Franklin      25
Lincoln       22
Jackson       20
Madison       19
Montgomery    17
Marion        17
Union         16
Monroe        16
Name: County, dtype: int64

In [16]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first')
X_encoded = encoder.fit_transform(census[['State']])

In [17]:
pd.DataFrame(X_encoded.todense()).head()

0    1    2    3    4    5    6    7    8    9   ...   41   42   43   44  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    45   46   47   48   49   50  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 51 columns]

In [18]:
encoder.categories_

[array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
        'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
        'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
        'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
        'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
        'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
        'New Jersey', 'New Mexico', 'New York', 'North Carolina',
        'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
        'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota',
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
        'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)]

pandas version:

In [19]:
pd.get_dummies(census['State'], drop_first=True).head()

Alaska  Arizona  Arkansas  California  Colorado  Connecticut  \
CensusId                                                                 
1001           0        0         0           0         0            0   
1003           0        0         0           0         0            0   
1005           0        0         0           0         0            0   
1007           0        0         0           0         0            0   
1009           0        0         0           0         0            0   

          Delaware  District of Columbia  Florida  Georgia  ...  South Dakota  \
CensusId                                                    ...                 
1001             0                     0        0        0  ...             0   
1003             0                     0        0        0  ...             0   
1005             0                     0        0        0  ...             0   
1007             0                     0        0        0  ...             0   
1009             0                     0        0        0  ...             0   

          Tennessee  Texas  Utah  Vermont  Virginia  Washington  \
CensusId                                                          
1001              0      0     0        0         0           0   
1003              0      0     0        0         0           0   
1005              0      0     0        0         0           0   
1007              0      0     0        0         0           0   
1009              0      0     0        0         0           0   

          West Virginia  Wisconsin  Wyoming  
CensusId                                     
1001                  0          0        0  
1003                  0          0        0  
1005                  0          0        0  
1007                  0          0        0  
1009                  0          0        0  

[5 rows x 51 columns]

### 2.3.4 label encoding

In [20]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(census[['County', 'State']])

In [21]:
pd.DataFrame(X_encoded).head()

0    1
0   85.0  0.0
1   92.0  0.0
2  103.0  0.0
3  154.0  0.0
4  168.0  0.0

### 2.3.5 mean encoding

advanced technique for categorical with lots of variables, most simple way, but never do that or it will cause overfitting, cross validation needed!

In [22]:
census['County'].map(census.groupby('County')['Unemployment'].mean()).head()

CensusId
1001     7.60
1003     7.95
1005    13.30
1007    10.35
1009     7.75
Name: County, dtype: float64

### 2.3.6 shuffling

this step is automatically performed by most modern ML libraries.

In [23]:
census.sample(frac=1.0).head(10)

State         County  TotalPop    Men  Women  Hispanic  \
CensusId                                                                   
19081              Iowa        Hancock     11092   5575   5517       3.7   
17069          Illinois         Hardin      4228   2184   2044       1.8   
72139       Puerto Rico  Trujillo Alto     71886  34036  37850      99.6   
47009         Tennessee         Blount    125188  60612  64576       3.0   
27083         Minnesota           Lyon     25699  12818  12881       6.3   
8095           Colorado       Phillips      4371   2259   2112      18.1   
36043          New York       Herkimer     64034  31598  32436       1.9   
54063     West Virginia         Monroe     13525   6686   6839       1.0   
54059     West Virginia          Mingo     25931  12686  13245       0.4   
30093           Montana     Silver Bow     34549  17539  17010       4.0   

          White  Black  Native  Asian  ...  Walk  OtherTransp  WorkAtHome  \
CensusId                               ...                                  
19081      94.2    0.6     0.1    0.3  ...   2.8          1.8         6.8   
17069      96.0    0.8     0.1    0.7  ...   2.1          1.4         6.2   
72139       0.4    0.0     0.0    0.0  ...   1.4          2.9         3.2   
47009      91.6    2.9     0.3    0.8  ...   0.9          1.0         3.7   
27083      86.6    2.8     0.5    3.3  ...   3.6          1.7         6.1   
8095       78.5    0.1     0.3    0.8  ...   8.1          1.2         3.0   
36043      95.0    0.9     0.2    0.4  ...   4.6          1.1         4.6   
54063      96.6    0.7     0.3    0.0  ...   1.4          0.1         3.9   
54059      96.0    1.4     0.1    0.4  ...   3.2          0.2         2.0   
30093      91.4    0.5     1.5    0.7  ...   2.8          3.1         3.5   

          MeanCommute  Employed  PrivateWork  PublicWork  SelfEmployed  \
CensusId                                                                 
19081            20.0      5640         77.2        11.6          10.5   
17069            25.2      1493         75.4        18.4           5.7   
72139            34.5     28059         68.9        21.0          10.1   
47009            24.3     56262         79.6        13.2           7.0   
27083            14.6     13788         79.1        12.1           8.7   
8095             14.5      1984         70.1        16.2          13.3   
36043            23.4     29074         76.3        16.7           6.9   
54063            31.6      5348         77.2        15.7           7.2   
54059            30.8      7951         73.5        21.6           4.7   
30093            15.2     16497         76.0        16.7           6.9   

          FamilyWork  Unemployment  
CensusId                            
19081            0.7           1.5  
17069            0.5          18.1  
72139            0.0           7.9  
47009            0.1           7.8  
27083            0.1           5.3  
8095             0.5           5.3  
36043            0.2           8.7  
54063            0.0           7.3  
54059            0.2          14.1  
30093            0.4           7.0  

[10 rows x 36 columns]

## 3. sampling

### 3.1 holdout

In [26]:
census.head()

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [27]:
train_validation, test = train_test_split(census)

In [28]:
train, validation = train_test_split(train_validation)

In [29]:
print(train.shape, validation.shape, test.shape)

(1699, 36) (567, 36) (756, 36)


### 3.2 cross validation

In [31]:
from sklearn.model_selection import KFold

In [32]:
kf = KFold(n_splits=10, shuffle=True)
for train_index, test_index in kf.split(census):
    display(train_index[:5], test_index[:5])
    display(census.iloc[train_index[:5],:], census.iloc[test_index[:5],:])

array([0, 1, 2, 3, 4])

array([19, 23, 27, 29, 37])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State      County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                        
1039      Alabama   Covington     37886  18339  19547       1.5   83.3   13.0   
1047      Alabama      Dallas     42154  19450  22704       0.3   28.6   69.2   
1055      Alabama      Etowah    103766  50207  53559       3.6   78.5   15.4   
1059      Alabama    Franklin     31634  15311  16323      15.7   78.5    4.1   
1077      Alabama  Lauderdale     92737  44419  48318       2.4   84.9    9.9   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1039         0.5    0.3  ...   1.5          1.9         2.2         25.5   
1047         0.2    0.3  ...   2.2          1.6         2.2         23.9   
1055         0.3    0.7  ...   0.4          0.5         3.8         23.4   
1059         0.7    0.1  ...   0.2          4.7         1.4         29.0   
1077         0.4    0.7  ...   1.6          1.0         2.2         24.6   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1039         14202         77.1        15.8           6.7         0.4   
1047         14094         76.6        16.7           6.2         0.4   
1055         41236         79.8        14.4           5.6         0.2   
1059         12249         78.5        14.6           6.9         0.0   
1077         39734         77.3        16.7           5.8         0.2   

          Unemployment  
CensusId                
1039              11.2  
1047              16.4  
1055               9.0  
1059               9.8  
1077               7.1  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([11, 16, 22, 26, 30])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State    County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                      
1023      Alabama   Choctaw     13395   6382   7013       0.4   55.9   42.9   
1033      Alabama   Colbert     54444  26303  28141       2.4   78.9   15.6   
1045      Alabama      Dale     49866  24708  25158       6.0   69.8   19.4   
1053      Alabama  Escambia     37935  19524  18411       1.2   60.7   33.4   
1061      Alabama    Geneva     26815  13174  13641       3.6   84.0    8.7   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1023         0.0    0.0  ...   1.9          1.4         0.8         30.7   
1033         0.6    0.3  ...   0.9          0.7         1.5         22.8   
1045         0.5    1.2  ...   1.6          1.7         2.6         20.4   
1053         3.2    0.1  ...   1.2          0.5         1.1         23.1   
1061         0.3    1.2  ...   0.9          1.8         3.4         25.8   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1023          4405         77.5        16.8           5.4         0.3   
1033         21290         78.6        16.1           5.2         0.0   
1045         18735         73.1        20.9           5.9         0.1   
1053         12294         74.5        19.0           6.4         0.1   
1061         10419         75.7        15.0           8.8         0.4   

          Unemployment  
CensusId                
1023              13.6  
1033               9.0  
1045              10.9  
1053              15.6  
1061              11.2  

[5 rows x 36 columns]

array([0, 2, 3, 4, 5])

array([ 1, 14, 21, 31, 34])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   
1011      Alabama  Bullock     10678   5660   5018       4.4   22.2   70.7   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   
1011         1.2    0.2  ...   5.0          1.7         2.8         27.5   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   
1011          3865         79.5        15.1           5.4         0.0   

          Unemployment  
CensusId                
1001               7.6  
1005              17.6  
1007               8.3  
1009               7.7  
1011              18.0  

[5 rows x 36 columns]

State    County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                      
1003      Alabama   Baldwin    195121  95314  99807       4.5   83.1    9.5   
1029      Alabama  Cleburne     15002   7334   7668       2.3   92.5    2.9   
1043      Alabama   Cullman     80965  40081  40884       4.3   92.2    1.1   
1063      Alabama    Greene      8697   4095   4602       0.7   17.8   80.6   
1069      Alabama   Houston    103534  49563  53971       3.2   67.7   26.2   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1029         0.2    0.4  ...   0.2          1.0         3.4         33.3   
1043         0.4    0.6  ...   1.5          1.0         2.6         26.4   
1063         0.1    0.2  ...   3.4          2.1         2.3         30.5   
1069         0.3    0.8  ...   0.7          1.3         2.1         21.4   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1003         85953         81.5        12.3           5.8         0.4   
1029          6065         76.3        15.3           8.4         0.0   
1043         32282         81.6        12.2           5.8         0.4   
1063          2412         75.8        17.2           7.0         0.0   
1069         44067         81.3        13.0           5.5         0.2   

          Unemployment  
CensusId                
1003               7.5  
1029               8.3  
1043               7.3  
1063              20.4  
1069               8.3  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([15, 39, 40, 52, 58])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State      County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                        
1031      Alabama      Coffee     50884  25174  25710       6.4   71.5   17.2   
1081      Alabama         Lee    150982  74277  76705       3.7   68.2   23.0   
1083      Alabama   Limestone     88805  44626  44179       5.8   77.4   12.8   
1109      Alabama        Pike     33155  15818  17337       0.9   57.1   38.2   
1123      Alabama  Tallapoosa     41153  19593  21560       2.5   69.0   27.4   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1031         0.8    1.2  ...   1.0          1.3         2.8         20.9   
1081         0.1    3.3  ...   2.2          1.0         3.1         21.7   
1083         0.5    1.2  ...   0.6          0.6         2.1         26.3   
1109         0.8    2.1  ...   2.2          0.9         3.2         19.2   
1123         0.3    0.0  ...   0.4          0.5         3.7         24.2   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1031         20912         70.3        23.5           5.7         0.5   
1081         68614         75.5        20.3           4.1         0.1   
1083         37664         77.9        16.4           5.5         0.2   
1109         14462         75.8        18.7           5.5         0.1   
1123         15837         78.4        15.6           5.5         0.5   

          Unemployment  
CensusId                
1031               7.1  
1081               7.3  
1083               7.8  
1109              10.2  
1123               9.0  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([35, 47, 48, 64, 68])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State                  County  TotalPop     Men   Women  Hispanic  \
CensusId                                                                        
1071      Alabama                 Jackson     52860   26076   26784       2.7   
1099      Alabama                  Monroe     22217   10639   11578       1.1   
1101      Alabama              Montgomery    228138  108296  119842       3.4   
2013       Alaska  Aleutians East Borough      3304    2198    1106      12.0   
2060       Alaska     Bristol Bay Borough       970     553     417       7.1   

          White  Black  Native  Asian  ...  Walk  OtherTransp  WorkAtHome  \
CensusId                               ...                                  
1071       89.4    3.1     1.1    0.4  ...   1.3          0.7         2.4   
1099       54.8   41.8     1.3    0.3  ...   1.0          0.7         1.7   
1101       36.9   55.8     0.2    2.2  ...   1.4          0.7         2.8   
2013       15.0    9.2    29.0   30.5  ...  71.2          2.2         2.8   
2060       53.4    0.5    29.0    0.7  ...   8.9          3.0         5.0   

          MeanCommute  Employed  PrivateWork  PublicWork  SelfEmployed  \
CensusId                                                                 
1071             25.4     20883         75.1        17.1           7.7   
1099             24.3      6551         77.3        18.4           4.1   
1101             19.3     99158         72.6        22.7           4.6   
2013              4.9      2519         78.6        15.4           5.9   
2060             10.4       541         49.7        39.2          11.1   

          FamilyWork  Unemployment  
CensusId                            
1071             0.0          10.1  
1099             0.2          20.7  
1101             0.1           8.8  
2013             0.2           2.9  
2060             0.0           5.4  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([ 6, 18, 24, 41, 42])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State   County  TotalPop     Men   Women  Hispanic  White  Black  \
CensusId                                                                       
1013      Alabama   Butler     20354    9502   10852       1.2   53.3   43.8   
1037      Alabama    Coosa     11027    5579    5448       2.1   65.2   30.7   
1049      Alabama   DeKalb     71068   35474   35594      14.0   80.9    1.8   
1087      Alabama    Macon     20018    9166   10852       1.6   16.1   80.9   
1089      Alabama  Madison    346438  169422  177016       4.7   65.6   23.9   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1013         0.1    0.4  ...   0.8          0.6         1.7         24.6   
1037         0.1    0.0  ...   0.9          1.0         2.1         28.6   
1049         1.1    0.3  ...   0.6          0.9         2.1         22.8   
1087         0.3    0.2  ...   5.7          1.4         1.7         21.8   
1089         0.6    2.5  ...   1.2          1.5         3.0         20.8   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1013          7813         77.4        16.2           6.2         0.2   
1037          3852         76.6        17.5           5.9         0.0   
1049         27778         78.8        12.6           8.5         0.1   
1087          7585         75.7        20.3           3.8         0.2   
1089        163753         75.6        19.5           4.7         0.2   

          Unemployment  
CensusId                
1013              10.9  
1037              17.0  
1049               7.7  
1087              16.9  
1089               8.5  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([ 9, 13, 50, 57, 80])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State               County  TotalPop    Men  Women  Hispanic  \
CensusId                                                                   
1019      Alabama             Cherokee     26008  12975  13033       1.5   
1027      Alabama                 Clay     13537   6671   6866       3.2   
1105      Alabama                Perry     10038   4651   5387       0.9   
1121      Alabama            Talladega     81437  39494  41943       2.2   
2185       Alaska  North Slope Borough      9667   6172   3495       3.6   

          White  Black  Native  Asian  ...  Walk  OtherTransp  WorkAtHome  \
CensusId                               ...                                  
1019       91.7    4.8     0.6    0.3  ...   0.6          0.7         2.5   
1027       79.9   14.4     0.7    0.0  ...   1.8          0.9         2.1   
1105       30.0   68.0     0.0    0.4  ...   3.5          2.6         1.1   
1121       63.7   31.9     0.3    0.4  ...   1.3          1.1         1.8   
2185       32.2    0.5    47.4    5.3  ...  37.9          7.9        14.3   

          MeanCommute  Employed  PrivateWork  PublicWork  SelfEmployed  \
CensusId                                                                 
1019             27.4     10155         73.1        18.5           7.9   
1027             30.3      5180         77.5        14.7           7.8   
1105             26.5      2865         76.3        19.0           4.7   
1121             24.6     30618         77.7        16.6           5.5   
2185              8.4      5499         73.8        25.2           0.9   

          FamilyWork  Unemployment  
CensusId                            
1019             0.5           7.9  
1027             0.0           9.4  
1105             0.0          11.2  
1121             0.2          13.8  
2185             0.0           9.3  

[5 rows x 36 columns]

array([0, 1, 2, 3, 4])

array([17, 25, 28, 32, 53])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1001      Alabama  Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  

[5 rows x 36 columns]

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1035      Alabama  Conecuh     12865   6176   6689       1.6   51.0   44.7   
1051      Alabama   Elmore     80763  39362  41401       2.8   73.6   21.0   
1057      Alabama  Fayette     16896   8477   8419       0.7   85.3   12.0   
1065      Alabama     Hale     15256   7183   8073       1.1   40.0   58.2   
1113      Alabama  Russell     58302  28347  29955       4.8   49.8   41.6   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1035         0.3    0.0  ...   0.6          0.3         1.3         29.7   
1051         0.2    0.5  ...   0.4          1.2         2.2         28.5   
1057         0.0    0.4  ...   0.3          0.2         1.9         28.4   
1065         0.3    0.3  ...   0.3          1.5         1.2         29.8   
1113         0.3    0.8  ...   1.1          0.9         2.8         24.3   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1035          3718         77.8        13.0           8.3         0.8   
1051         33636         70.4        24.1           5.5         0.0   
1057          6122         81.9        14.2           3.8         0.1   
1065          5282         76.3        17.6           5.8         0.3   
1113         22927         75.5        20.3           4.2         0.1   

          Unemployment  
CensusId                
1035              22.6  
1051               8.3  
1057              10.0  
1065              13.3  
1113              11.1  

[5 rows x 36 columns]

array([1, 2, 3, 4, 5])

array([ 0,  7, 12, 33, 36])

State   County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                     
1003      Alabama  Baldwin    195121  95314  99807       4.5   83.1    9.5   
1005      Alabama  Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama     Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama   Blount     57710  28512  29198       8.6   87.9    1.5   
1011      Alabama  Bullock     10678   5660   5018       4.4   22.2   70.7   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   
1011         1.2    0.2  ...   5.0          1.7         2.8         27.5   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1003         85953         81.5        12.3           5.8         0.4   
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   
1011          3865         79.5        15.1           5.4         0.0   

          Unemployment  
CensusId                
1003               7.5  
1005              17.6  
1007               8.3  
1009               7.7  
1011              18.0  

[5 rows x 36 columns]

State     County  TotalPop     Men   Women  Hispanic  White  \
CensusId                                                                  
1001      Alabama    Autauga     55221   26745   28476       2.6   75.8   
1015      Alabama    Calhoun    116648   56274   60374       3.5   73.0   
1025      Alabama     Clarke     25070   11834   13236       0.3   53.4   
1067      Alabama      Henry     17252    8259    8993       2.5   68.3   
1073      Alabama  Jefferson    659026  311581  347445       3.8   51.0   

          Black  Native  Asian  ...  Walk  OtherTransp  WorkAtHome  \
CensusId                        ...                                  
1001       18.5     0.4    1.0  ...   0.5          1.3         1.8   
1015       20.3     0.2    0.9  ...   1.2          1.2         2.7   
1025       45.3     0.0    0.4  ...   1.3          2.6         1.1   
1067       28.4     0.0    0.0  ...   1.0          2.6         2.2   
1073       42.2     0.2    1.6  ...   1.3          1.0         2.5   

          MeanCommute  Employed  PrivateWork  PublicWork  SelfEmployed  \
CensusId                                                                 
1001             26.5     23986         73.6        20.9           5.5   
1015             24.1     47401         74.1        20.8           5.0   
1025             23.0      8161         83.1        13.6           3.3   
1067             26.9      6922         78.9        15.5           5.4   
1073             23.6    293202         80.9        14.4           4.6   

          FamilyWork  Unemployment  
CensusId                            
1001             0.0           7.6  
1015             0.1          12.3  
1025             0.0          19.4  
1067             0.2           8.1  
1073             0.2           9.1  

[5 rows x 36 columns]

array([0, 1, 6, 7, 9])

array([2, 3, 4, 5, 8])

State    County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                      
1001      Alabama   Autauga     55221  26745  28476       2.6   75.8   18.5   
1003      Alabama   Baldwin    195121  95314  99807       4.5   83.1    9.5   
1013      Alabama    Butler     20354   9502  10852       1.2   53.3   43.8   
1015      Alabama   Calhoun    116648  56274  60374       3.5   73.0   20.3   
1019      Alabama  Cherokee     26008  12975  13033       1.5   91.7    4.8   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1001         0.4    1.0  ...   0.5          1.3         1.8         26.5   
1003         0.6    0.7  ...   1.0          1.4         3.9         26.4   
1013         0.1    0.4  ...   0.8          0.6         1.7         24.6   
1015         0.2    0.9  ...   1.2          1.2         2.7         24.1   
1019         0.6    0.3  ...   0.6          0.7         2.5         27.4   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1001         23986         73.6        20.9           5.5         0.0   
1003         85953         81.5        12.3           5.8         0.4   
1013          7813         77.4        16.2           6.2         0.2   
1015         47401         74.1        20.8           5.0         0.1   
1019         10155         73.1        18.5           7.9         0.5   

          Unemployment  
CensusId                
1001               7.6  
1003               7.5  
1013              10.9  
1015              12.3  
1019               7.9  

[5 rows x 36 columns]

State    County  TotalPop    Men  Women  Hispanic  White  Black  \
CensusId                                                                      
1005      Alabama   Barbour     26932  14497  12435       4.6   46.2   46.7   
1007      Alabama      Bibb     22604  12073  10531       2.2   74.5   21.4   
1009      Alabama    Blount     57710  28512  29198       8.6   87.9    1.5   
1011      Alabama   Bullock     10678   5660   5018       4.4   22.2   70.7   
1017      Alabama  Chambers     34079  16258  17821       0.4   57.3   40.3   

          Native  Asian  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
CensusId                 ...                                               
1005         0.2    0.4  ...   1.8          1.5         1.6         24.1   
1007         0.4    0.1  ...   0.6          1.5         0.7         28.8   
1009         0.3    0.1  ...   0.9          0.4         2.3         34.9   
1011         1.2    0.2  ...   5.0          1.7         2.8         27.5   
1017         0.2    0.8  ...   0.3          0.4         2.1         25.1   

          Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  \
CensusId                                                                
1005          8597         71.8        20.8           7.3         0.1   
1007          8294         76.8        16.1           6.7         0.4   
1009         22189         82.0        13.5           4.2         0.4   
1011          3865         79.5        15.1           5.4         0.0   
1017         13689         85.1        12.1           2.8         0.0   

          Unemployment  
CensusId                
1005              17.6  
1007               8.3  
1009               7.7  
1011              18.0  
1017               8.9  

[5 rows x 36 columns]