# Introduction to Pandas

In [1]:
import numpy as np
import pandas as pd

In [4]:
array = np.random.random(10)

array

array([0.38899996, 0.07734314, 0.20649624, 0.81486181, 0.38051802,
       0.91206249, 0.29481726, 0.62587522, 0.48424753, 0.91590552])

In [8]:
serie = pd.Series(array)

serie

0    0.389000
1    0.077343
2    0.206496
3    0.814862
4    0.380518
5    0.912062
6    0.294817
7    0.625875
8    0.484248
9    0.915906
dtype: float64

In [9]:
serie.index

RangeIndex(start=0, stop=10, step=1)

In [10]:
serie.values

array([0.38899996, 0.07734314, 0.20649624, 0.81486181, 0.38051802,
       0.91206249, 0.29481726, 0.62587522, 0.48424753, 0.91590552])

In [12]:
serie[3]

0.8148618066974527

In [16]:
colnames = ['col1', 'col2', 'col3', 'col4', 'col5']
df = pd.DataFrame(np.random.random((10,5)), columns=colnames)
df

col1      col2      col3      col4      col5
0  0.780105  0.502205  0.011880  0.697494  0.011354
1  0.134814  0.120873  0.709582  0.558200  0.824548
2  0.025543  0.099954  0.609852  0.071576  0.246238
3  0.403553  0.074001  0.825961  0.016868  0.562347
4  0.892112  0.222460  0.806016  0.804471  0.905120
5  0.632347  0.245112  0.195675  0.279891  0.082702
6  0.189453  0.432622  0.257156  0.737871  0.175141
7  0.003906  0.668110  0.086067  0.145446  0.665116
8  0.419541  0.531132  0.845902  0.296990  0.423047
9  0.193364  0.163736  0.456456  0.400243  0.673149

In [5]:
df.index.to_list()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
df.values

array([[0.78010502, 0.50220497, 0.01188024, 0.69749356, 0.01135419],
       [0.13481352, 0.12087269, 0.7095818 , 0.55820031, 0.82454794],
       [0.02554294, 0.09995422, 0.6098518 , 0.0715758 , 0.24623817],
       [0.40355252, 0.07400113, 0.82596066, 0.01686822, 0.56234693],
       [0.8921124 , 0.22245955, 0.80601578, 0.80447129, 0.90511989],
       [0.63234694, 0.24511195, 0.19567473, 0.27989147, 0.08270235],
       [0.18945265, 0.43262173, 0.25715638, 0.73787121, 0.17514097],
       [0.00390604, 0.6681098 , 0.0860673 , 0.14544591, 0.66511569],
       [0.41954055, 0.53113227, 0.84590184, 0.29698953, 0.42304659],
       [0.19336374, 0.16373595, 0.45645567, 0.40024342, 0.67314853]])

In [18]:
# this is a series
series = df['col1']

series

0    0.780105
1    0.134814
2    0.025543
3    0.403553
4    0.892112
5    0.632347
6    0.189453
7    0.003906
8    0.419541
9    0.193364
Name: col1, dtype: float64

In [19]:
# beware of the list now
df[['col1', 'col2', 'col3']]

col1      col2      col3
0  0.780105  0.502205  0.011880
1  0.134814  0.120873  0.709582
2  0.025543  0.099954  0.609852
3  0.403553  0.074001  0.825961
4  0.892112  0.222460  0.806016
5  0.632347  0.245112  0.195675
6  0.189453  0.432622  0.257156
7  0.003906  0.668110  0.086067
8  0.419541  0.531132  0.845902
9  0.193364  0.163736  0.456456

In [20]:
df['col1', 'col2', 'col3']

KeyError: ('col1', 'col2', 'col3')

In [24]:
# this is a dataframe
df[['col1']]

col1
0  0.780105
1  0.134814
2  0.025543
3  0.403553
4  0.892112
5  0.632347
6  0.189453
7  0.003906
8  0.419541
9  0.193364

In [26]:
lst = [208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000, 129900, 118000]

price_df = pd.DataFrame(lst, columns=['SalePrice'])
price_df

SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000
5     143000
6     307000
7     200000
8     129900
9     118000

In [28]:
lst_lst = [[8450, 'CollgCr', 2003, 7, 208500],
           [9600, 'Veenker', 1976, 6, 181500],
           [11250, 'CollgCr', 2001, 7, 223500],
           [9550, 'Crawfor', 1915, 7, 140000],
           [14260, 'NoRidge', 2000, 8, 250000],
           [14115, 'Mitchel', 1993, 5, 143000],
           [10084, 'Somerst', 2004, 8, 307000],
           [10382, 'NWAmes', 1973, 7, 200000],
           [6120, 'OldTown', 1931, 7, 129900],
           [7420, 'BrkSide', 1939, 5, 118000]]

colnames = ['LotSize','Neighborhood','YearBuilt','Quality','SalePrice']
df = pd.DataFrame(lst_lst, columns=colnames)

df

LotSize Neighborhood  YearBuilt  Quality  SalePrice
0     8450      CollgCr       2003        7     208500
1     9600      Veenker       1976        6     181500
2    11250      CollgCr       2001        7     223500
3     9550      Crawfor       1915        7     140000
4    14260      NoRidge       2000        8     250000
5    14115      Mitchel       1993        5     143000
6    10084      Somerst       2004        8     307000
7    10382       NWAmes       1973        7     200000
8     6120      OldTown       1931        7     129900
9     7420      BrkSide       1939        5     118000

In [29]:
df.columns

Index(['LotSize', 'Neighborhood', 'YearBuilt', 'Quality', 'SalePrice'], dtype='object')

In [30]:
df.dtypes

LotSize          int64
Neighborhood    object
YearBuilt        int64
Quality          int64
SalePrice        int64
dtype: object

In [39]:
house_dict = {'Baker House': [7420, 'BrkSide', 1939, 5, 123054],
              'Beazley House': [14115, 'Mitchel', 1993, 5, 143000],
              'Dominguez House': [14260, 'NoRidge', 2000, 8, 250000],
              'Hamilton House': [6120, 'OldTown', 1931, 7, 129900],
              'James House': [11250, 'CollgCr', 2001, 7, 223500],
              'Martinez House': [9600, 'Veenker', 1976, 6, 181500],
              'Roberts House': [9550, 'Crawfor', 1915, 7, 140000],
              'Smith House': [8450, 'CollgCr', 2003, 7, 208500],
              'Snyder House': [10084, 'Somerst', 2004, 8, 307000],
              'Zuckerman House': [10382, 'NWAmes', 1973, 7, 200000]}

In [40]:
df = pd.DataFrame(house_dict)
df

Baker House Beazley House Dominguez House Hamilton House James House  \
0        7420         14115           14260           6120       11250   
1     BrkSide       Mitchel         NoRidge        OldTown     CollgCr   
2        1939          1993            2000           1931        2001   
3           5             5               8              7           7   
4      123054        143000          250000         129900      223500   

  Martinez House Roberts House Smith House Snyder House Zuckerman House  
0           9600          9550        8450        10084           10382  
1        Veenker       Crawfor     CollgCr      Somerst          NWAmes  
2           1976          1915        2003         2004            1973  
3              6             7           7            8               7  
4         181500        140000      208500       307000          200000

In [41]:
df.dtypes

Baker House        object
Beazley House      object
Dominguez House    object
Hamilton House     object
James House        object
Martinez House     object
Roberts House      object
Smith House        object
Snyder House       object
Zuckerman House    object
dtype: object

In [42]:
df.T

0        1     2  3       4
Baker House       7420  BrkSide  1939  5  123054
Beazley House    14115  Mitchel  1993  5  143000
Dominguez House  14260  NoRidge  2000  8  250000
Hamilton House    6120  OldTown  1931  7  129900
James House      11250  CollgCr  2001  7  223500
Martinez House    9600  Veenker  1976  6  181500
Roberts House     9550  Crawfor  1915  7  140000
Smith House       8450  CollgCr  2003  7  208500
Snyder House     10084  Somerst  2004  8  307000
Zuckerman House  10382   NWAmes  1973  7  200000

In [43]:
df.T.index

Index(['Baker House', 'Beazley House', 'Dominguez House', 'Hamilton House',
       'James House', 'Martinez House', 'Roberts House', 'Smith House',
       'Snyder House', 'Zuckerman House'],
      dtype='object')

In [44]:
df.T.columns

RangeIndex(start=0, stop=5, step=1)

In [45]:
df = df.T
df.columns = colnames

df

LotSize Neighborhood YearBuilt Quality SalePrice
Baker House        7420      BrkSide      1939       5    123054
Beazley House     14115      Mitchel      1993       5    143000
Dominguez House   14260      NoRidge      2000       8    250000
Hamilton House     6120      OldTown      1931       7    129900
James House       11250      CollgCr      2001       7    223500
Martinez House     9600      Veenker      1976       6    181500
Roberts House      9550      Crawfor      1915       7    140000
Smith House        8450      CollgCr      2003       7    208500
Snyder House      10084      Somerst      2004       8    307000
Zuckerman House   10382       NWAmes      1973       7    200000

In [46]:
# orient='index' means take the dict keys as index (not as column names)
df = pd.DataFrame.from_dict(house_dict, orient='index')
df.columns = colnames

df

LotSize Neighborhood  YearBuilt  Quality  SalePrice
Baker House         7420      BrkSide       1939        5     123054
Beazley House      14115      Mitchel       1993        5     143000
Dominguez House    14260      NoRidge       2000        8     250000
Hamilton House      6120      OldTown       1931        7     129900
James House        11250      CollgCr       2001        7     223500
Martinez House      9600      Veenker       1976        6     181500
Roberts House       9550      Crawfor       1915        7     140000
Smith House         8450      CollgCr       2003        7     208500
Snyder House       10084      Somerst       2004        8     307000
Zuckerman House    10382       NWAmes       1973        7     200000

In [47]:
# Total price of all houses sold
print(df['SalePrice'].sum())

# Average lot size of houses sold
print(df['LotSize'].mean())

# The latest year a house in the data set was built
print(df['YearBuilt'].max())

# The eariliest year a house in the data set was built
print(df['YearBuilt'].min())

1906454
10123.1
2004
1915


In [48]:
df.sort_values(by='SalePrice', ascending=False)

LotSize Neighborhood  YearBuilt  Quality  SalePrice
Snyder House       10084      Somerst       2004        8     307000
Dominguez House    14260      NoRidge       2000        8     250000
James House        11250      CollgCr       2001        7     223500
Smith House         8450      CollgCr       2003        7     208500
Zuckerman House    10382       NWAmes       1973        7     200000
Martinez House      9600      Veenker       1976        6     181500
Beazley House      14115      Mitchel       1993        5     143000
Roberts House       9550      Crawfor       1915        7     140000
Hamilton House      6120      OldTown       1931        7     129900
Baker House         7420      BrkSide       1939        5     123054

In [49]:
df['LotSize'].sort_values(ascending=True)

Hamilton House      6120
Baker House         7420
Smith House         8450
Roberts House       9550
Martinez House      9600
Snyder House       10084
Zuckerman House    10382
James House        11250
Beazley House      14115
Dominguez House    14260
Name: LotSize, dtype: int64

In [50]:
series = df['LotSize']

series.sort_values()

Hamilton House      6120
Baker House         7420
Smith House         8450
Roberts House       9550
Martinez House      9600
Snyder House       10084
Zuckerman House    10382
James House        11250
Beazley House      14115
Dominguez House    14260
Name: LotSize, dtype: int64

## Bonus

### filter

In [20]:
# series (watch the index)

series[series > 0.5]

0    0.961524
1    0.649325
2    0.712940
3    0.570239
4    0.640056
5    0.571289
6    0.725276
7    0.842611
9    0.674560
Name: col1, dtype: float64

In [21]:
# dataframe

df[df['LotSize'] > 10000]

LotSize Neighborhood  YearBuilt  Quality  SalePrice
Beazley House      14115      Mitchel       1993        5     143000
Dominguez House    14260      NoRidge       2000        8     250000
James House        11250      CollgCr       2001        7     223500
Snyder House       10084      Somerst       2004        8     307000
Zuckerman House    10382       NWAmes       1973        7     200000

### map

In [22]:
series.apply(lambda x: x * 2)

0    1.923048
1    1.298649
2    1.425880
3    1.140478
4    1.280113
5    1.142578
6    1.450552
7    1.685222
8    0.640706
9    1.349120
Name: col1, dtype: float64

In [23]:
df[['LotSize', 'Quality']].apply(lambda x: x * 2)

LotSize  Quality
Baker House        14840       10
Beazley House      28230       10
Dominguez House    28520       16
Hamilton House     12240       14
James House        22500       14
Martinez House     19200       12
Roberts House      19100       14
Smith House        16900       14
Snyder House       20168       16
Zuckerman House    20764       14