# Numpy

In [4]:
!pip install numpy

In [31]:
import numpy as np

The basic data structures in Numpy are arrays, which can be used to represent tabular data. You can think of arrays as lists of lists.
The size of an array is the total number of elements in every list. The shape of an array is the size of the array along each dimension

In [11]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((2))

array([0., 0.])

In [14]:
[0.0, 0.0]

[0.0, 0.0]

In [23]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [4]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
import numpy.random
from numpy.random import random as my_random_method

print(numpy.random.random(3))
print(my_random_method(3))

[0.57600032 0.81963452 0.65277544]
[0.49912089 0.13451354 0.54565852]


In [38]:
a = np.random.random((10,4))
print(a)

[[0.97109069 0.86527659 0.02099163 0.67322725]
 [0.30968203 0.5606498  0.74171493 0.04884043]
 [0.1004023  0.79443719 0.14839844 0.76986872]
 [0.0837444  0.97955145 0.48342105 0.72424053]
 [0.60034284 0.41740192 0.92702337 0.25414165]
 [0.12282832 0.70748602 0.46775524 0.19262186]
 [0.50563895 0.88225402 0.67666386 0.7963154 ]
 [0.10000227 0.54258897 0.89069389 0.1266725 ]
 [0.63854477 0.36128873 0.94338786 0.90177198]
 [0.81027891 0.31776209 0.29505865 0.70696459]]


In [6]:
print(a.shape)
print(a.size)

(10, 4)
40


In [7]:
b = np.random.random((5,2,3))
print(b)

[[[0.31917558 0.01971247 0.2654787 ]
  [0.80424422 0.02162372 0.12193553]]

 [[0.50464972 0.34662324 0.41675035]
  [0.45350205 0.9887594  0.35099502]]

 [[0.71747115 0.64481611 0.17843699]
  [0.13010684 0.24772277 0.95510155]]

 [[0.89536234 0.86447625 0.08329889]
  [0.28611028 0.08485153 0.71151901]]

 [[0.72153384 0.09311449 0.14443456]
  [0.75751635 0.67026144 0.65652973]]]


In [39]:
# first row
print(a[0])

[0.97109069 0.86527659 0.02099163 0.67322725]


In [35]:
# first column
a[:,0]

array([0.46094918, 0.10330849, 0.39735844, 0.45464174, 0.42100285,
       0.09459955, 0.9926801 , 0.79053392, 0.09598089, 0.92154649])

In [37]:
print(a[4,2])

0.4562081356538136


In [43]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9,10]]
d = np.array(lst_lst)
d

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [44]:
d.shape

(3,)

In [45]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.sum(d)

45

In [47]:
# why not np
sum(d[:,0])

12

In [48]:
np.sum(d[:,0])

12

In [49]:
np.sum(d[1,:])

15

In [50]:
np.sum(d[1])

15

In [51]:
np.sum(d, axis=0)

array([12, 15, 18])

In [52]:
np.sum(d, axis=1)

array([ 6, 15, 24])

In [16]:
print(np.mean(d))

5.0


In [17]:
print(np.mean(d, axis=0))

[4. 5. 6.]


In [18]:
np.mean(d, axis=1)

[2. 5. 8.]


## Operator overload

In [64]:
x = np.array([[1,2], [1,0]])
x

array([[1, 2],
       [1, 0]])

In [65]:
y = np.array([[1,2], [1,1]])
y

array([[1, 2],
       [1, 1]])

In [21]:
print(x + y)
np.add(x,y)

[[2 4]
 [2 1]]


array([[2, 4],
       [2, 1]])

In [58]:
# pedro's recommendation
x + y

array([[2, 4],
       [2, 1]])

In [22]:
print(x - y)
np.subtract(x,y)

[[ 0  0]
 [ 0 -1]]


array([[ 0,  0],
       [ 0, -1]])

In [23]:
print(x * y)
np.multiply(x,y)

[[1 4]
 [1 0]]


array([[1, 4],
       [1, 0]])

In [24]:
print(x / y)
np.divide(x,y)

[[1. 1.]
 [1. 0.]]


array([[1., 1.],
       [1., 0.]])

In [59]:
# this is for Emilio health

In [60]:
x = np.array([[1,2,3], [1,1,1]])
x

array([[1, 2, 3],
       [1, 1, 1]])

In [61]:
y = np.array([[1,2], [1,1], [0,0]])
y

array([[1, 2],
       [1, 1],
       [0, 0]])

In [27]:
np.matmul(x,y)

array([[3, 4],
       [2, 3]])

In [62]:
x * y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 